/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1.etb;


import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;

/**
 *
 * @author user
 */
public class etbmain extends javax.swing.JFrame {

    /**
     * Creates new form etbmain
     */
    public etbmain() throws IOException {
        initComponents();

            jTabbedPane1.addTab(" Dictionary",new dictable());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Option = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 153));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setBackground(new java.awt.Color(204, 255, 204));
        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(204, 255, 204));
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        Option.setBackground(new java.awt.Color(153, 255, 153));
        Option.setText("Option");
        jMenuBar1.add(Option);

        jMenu3.setBackground(new java.awt.Color(153, 255, 153));
        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        
        
        
        try{
        //    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
      //      UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
            LookAndFeel l=UIManager.getLookAndFeel();
            System.out.println(l.getID());
            if(l.getID().compareTo("Metal")==0)
            {
                if(appmemory.getstore().theme==1)
             UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                if(appmemory.getstore().theme==2)
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
                if(appmemory.getstore().theme==3)
                UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
            }
        }
        catch(Exception e)
        {

        }
       
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.EventQueue.invokeLater(new Runnable() {


            public void run() {
                try {
                    etbmain e=new etbmain();
                    //e.setSize(600,800);
                    e.setVisible(true);
                    
                } catch (IOException ex) {
                    Logger.getLogger(etbmain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Option;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
